package egg

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestCodexLifecycleArgsTrustOnlyGeneratedHooks(t *testing.T) {
	home := t.TempDir()
	config := filepath.Join(home, ".codex", "config.toml")
	if err := os.MkdirAll(filepath.Dir(config), 0700); err != nil {
		t.Fatal(err)
	}
	original := []byte("notify = ['existing-notifier']\n")
	if err := os.WriteFile(config, original, 0600); err != nil {
		t.Fatal(err)
	}
	args, err := CodexLifecycleArgs([]string{"resume", "thread-exact", "-m", "existing-model"}, home, "egg-exact")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(args[:4], " ") != "resume thread-exact -m existing-model" || len(args) != 4+4*len(codexLifecycleEvents) {
		t.Fatalf("unexpected args: %v", args)
	}
	for _, arg := range args {
		if strings.Contains(arg, "bypass-hook-trust") || strings.Contains(arg, "notify=") || strings.Contains(arg, "features.hooks") {
			t.Fatalf("changed existing hook policy: %s", arg)
		}
	}
	data, err := os.ReadFile(config)
	if err != nil || string(data) != string(original) {
		t.Fatalf("user config changed: %s, %v", data, err)
	}
	// This hash is from the installed 0.159.3 app-server's hooks/list, rather
	// than an expectation generated by the implementation under test.
	hash, err := codexLifecycleHookHash("session_start", "true")
	if err != nil || hash != "sha256:e40688e342bc653567f4d9e8590f9b0ceb640df45804b65d9361fbe9f641edf1" {
		t.Fatalf("Codex trust identity changed: %q, %v", hash, err)
	}
	for _, supplied := range [][]string{{"--disable", "hooks"}, {"-c", "features.hooks=false"}, {"-c", "hooks.Stop=[]"}} {
		got, err := CodexLifecycleArgs(supplied, home, "egg-exact")
		if err != nil || strings.Join(got, " ") != strings.Join(supplied, " ") {
			t.Fatalf("explicit hook settings replaced: %v, %v", got, err)
		}
	}
}

func TestCodexLifecycleNativeHooksBindThreadAndReportStatus(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	args, err := CodexLifecycleArgs(nil, home, filepath.Base(dir))
	if err != nil {
		t.Fatal(err)
	}
	commands := map[string]string{}
	for i, event := range codexLifecycleEvents {
		definition := args[i*4+1]
		quoted := strings.TrimSuffix(strings.SplitN(definition, "command=", 2)[1], ",timeout=3}]}]")
		command, err := strconv.Unquote(quoted)
		if err != nil {
			t.Fatal(err)
		}
		commands[event.name] = command
	}
	drive := func(event, id, tool string) {
		t.Helper()
		payload, _ := json.Marshal(map[string]string{"hook_event_name": event, "session_id": id, "tool_name": tool})
		cmd := exec.Command("/bin/sh", "-c", commands[event])
		cmd.Stdin = strings.NewReader(string(payload))
		if output, err := cmd.CombinedOutput(); err != nil || len(output) != 0 {
			t.Fatalf("hook: %s, %v", output, err)
		}
	}
	read := func(alive bool, cursor int64) SessionView {
		t.Helper()
		v, err := ReadSessionLifecycle(dir, "codex", "/fixture", home, "", alive, cursor, 100)
		if err != nil {
			t.Fatal(err)
		}
		return v
	}
	if v := read(true, 0); v.Status != "unknown" {
		t.Fatalf("missing hooks guessed status: %+v", v)
	}
	drive("SessionStart", "thread-exact", "")
	for _, tc := range []struct{ event, tool, status string }{
		{"UserPromptSubmit", "", "working"},
		{"PermissionRequest", "Bash", "blocked"},
		{"PostToolUse", "Bash", "working"},
		{"PreToolUse", "request_user_input", "blocked"},
		{"PostToolUse", "request_user_input", "working"},
		{"Stop", "", "idle"},
		{"PreCompact", "", "working"},
		{"Interrupt", "", "idle"},
		{"SessionEnd", "", "done"},
	} {
		drive(tc.event, "thread-exact", tc.tool)
		v := read(true, 0)
		if v.Status != tc.status || v.ProviderSessionID != "thread-exact" || v.StateSource != "codex_hook" {
			t.Fatalf("%s: %+v", tc.event, v)
		}
	}
	drive("UserPromptSubmit", "foreign-child", "")
	v := read(false, 0)
	if v.Status != "done" || v.Ready || v.ProviderSessionID != "thread-exact" {
		t.Fatalf("foreign thread regressed end: %+v", v)
	}
	if replay := read(false, v.HeadCursor); len(replay.Events) != 0 {
		t.Fatalf("duplicate import: %+v", replay)
	}
	if err := RecordSessionProcessEvent(dir, "session_exit", "failed", "killed"); err != nil {
		t.Fatal(err)
	}
	if v = read(false, 0); v.Status != "exited" {
		t.Fatal(fmt.Sprintf("failed process reported done: %+v", v))
	}
}
