// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: egg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_egg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agent          string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	BufferBytes    int64                  `protobuf:"varint,3,opt,name=buffer_bytes,json=bufferBytes,proto3" json:"buffer_bytes,omitempty"`
	TotalWritten   int64                  `protobuf:"varint,4,opt,name=total_written,json=totalWritten,proto3" json:"total_written,omitempty"`
	TotalTrimmed   int64                  `protobuf:"varint,5,opt,name=total_trimmed,json=totalTrimmed,proto3" json:"total_trimmed,omitempty"`
	Readers        int32                  `protobuf:"varint,6,opt,name=readers,proto3" json:"readers,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RenderedConfig string                 `protobuf:"bytes,8,opt,name=rendered_config,json=renderedConfig,proto3" json:"rendered_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_egg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StatusResponse) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *StatusResponse) GetBufferBytes() int64 {
	if x != nil {
		return x.BufferBytes
	}
	return 0
}

func (x *StatusResponse) GetTotalWritten() int64 {
	if x != nil {
		return x.TotalWritten
	}
	return 0
}

func (x *StatusResponse) GetTotalTrimmed() int64 {
	if x != nil {
		return x.TotalTrimmed
	}
	return 0
}

func (x *StatusResponse) GetReaders() int32 {
	if x != nil {
		return x.Readers
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetRenderedConfig() string {
	if x != nil {
		return x.RenderedConfig
	}
	return ""
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_egg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{2}
}

func (x *KillRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_egg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{3}
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_egg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{4}
}

func (x *ResizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_egg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{5}
}

type SessionMsg struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SessionMsg_Output
	//	*SessionMsg_Input
	//	*SessionMsg_Resize
	//	*SessionMsg_ExitCode
	//	*SessionMsg_Attach
	//	*SessionMsg_Detach
	Payload       isSessionMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMsg) Reset() {
	*x = SessionMsg{}
	mi := &file_egg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMsg) ProtoMessage() {}

func (x *SessionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMsg.ProtoReflect.Descriptor instead.
func (*SessionMsg) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{6}
}

func (x *SessionMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMsg) GetPayload() isSessionMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionMsg) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *SessionMsg) GetInput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *SessionMsg) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *SessionMsg) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *SessionMsg) GetAttach() bool {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Attach); ok {
			return x.Attach
		}
	}
	return false
}

func (x *SessionMsg) GetDetach() bool {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Detach); ok {
			return x.Detach
		}
	}
	return false
}

type isSessionMsg_Payload interface {
	isSessionMsg_Payload()
}

type SessionMsg_Output struct {
	Output []byte `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type SessionMsg_Input struct {
	Input []byte `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type SessionMsg_Resize struct {
	Resize *Resize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type SessionMsg_ExitCode struct {
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type SessionMsg_Attach struct {
	Attach bool `protobuf:"varint,6,opt,name=attach,proto3,oneof"`
}

type SessionMsg_Detach struct {
	Detach bool `protobuf:"varint,7,opt,name=detach,proto3,oneof"`
}

func (*SessionMsg_Output) isSessionMsg_Payload() {}

func (*SessionMsg_Input) isSessionMsg_Payload() {}

func (*SessionMsg_Resize) isSessionMsg_Payload() {}

func (*SessionMsg_ExitCode) isSessionMsg_Payload() {}

func (*SessionMsg_Attach) isSessionMsg_Payload() {}

func (*SessionMsg_Detach) isSessionMsg_Payload() {}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_egg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{7}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

var File_egg_proto protoreflect.FileDescriptor

const file_egg_proto_rawDesc = "" +
	"\n" +
	"\tegg.proto\x12\x03egg\"\x0f\n" +
	"\rStatusRequest\"\x9c\x02\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12!\n" +
	"\fbuffer_bytes\x18\x03 \x01(\x03R\vbufferBytes\x12#\n" +
	"\rtotal_written\x18\x04 \x01(\x03R\ftotalWritten\x12#\n" +
	"\rtotal_trimmed\x18\x05 \x01(\x03R\ftotalTrimmed\x12\x18\n" +
	"\areaders\x18\x06 \x01(\x05R\areaders\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0frendered_config\x18\b \x01(\tR\x0erenderedConfig\",\n" +
	"\vKillRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x0e\n" +
	"\fKillResponse\"V\n" +
	"\rResizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\"\x10\n" +
	"\x0eResizeResponse\"\xe2\x01\n" +
	"\n" +
	"SessionMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\x06output\x18\x02 \x01(\fH\x00R\x06output\x12\x16\n" +
	"\x05input\x18\x03 \x01(\fH\x00R\x05input\x12%\n" +
	"\x06resize\x18\x04 \x01(\v2\v.egg.ResizeH\x00R\x06resize\x12\x1d\n" +
	"\texit_code\x18\x05 \x01(\x05H\x00R\bexitCode\x12\x18\n" +
	"\x06attach\x18\x06 \x01(\bH\x00R\x06attach\x12\x18\n" +
	"\x06detach\x18\a \x01(\bH\x00R\x06detachB\t\n" +
	"\apayload\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols2\xc9\x01\n" +
	"\x03Egg\x12+\n" +
	"\x04Kill\x12\x10.egg.KillRequest\x1a\x11.egg.KillResponse\x121\n" +
	"\x06Resize\x12\x12.egg.ResizeRequest\x1a\x13.egg.ResizeResponse\x12/\n" +
	"\aSession\x12\x0f.egg.SessionMsg\x1a\x0f.egg.SessionMsg(\x010\x01\x121\n" +
	"\x06Status\x12\x12.egg.StatusRequest\x1a\x13.egg.StatusResponseB0Z.github.com/ehrlich-b/wingthing/internal/egg/pbb\x06proto3"

var (
	file_egg_proto_rawDescOnce sync.Once
	file_egg_proto_rawDescData []byte
)

func file_egg_proto_rawDescGZIP() []byte {
	file_egg_proto_rawDescOnce.Do(func() {
		file_egg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egg_proto_rawDesc), len(file_egg_proto_rawDesc)))
	})
	return file_egg_proto_rawDescData
}

var file_egg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_egg_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: egg.StatusRequest
	(*StatusResponse)(nil), // 1: egg.StatusResponse
	(*KillRequest)(nil),    // 2: egg.KillRequest
	(*KillResponse)(nil),   // 3: egg.KillResponse
	(*ResizeRequest)(nil),  // 4: egg.ResizeRequest
	(*ResizeResponse)(nil), // 5: egg.ResizeResponse
	(*SessionMsg)(nil),     // 6: egg.SessionMsg
	(*Resize)(nil),         // 7: egg.Resize
}
var file_egg_proto_depIdxs = []int32{
	7, // 0: egg.SessionMsg.resize:type_name -> egg.Resize
	2, // 1: egg.Egg.Kill:input_type -> egg.KillRequest
	4, // 2: egg.Egg.Resize:input_type -> egg.ResizeRequest
	6, // 3: egg.Egg.Session:input_type -> egg.SessionMsg
	0, // 4: egg.Egg.Status:input_type -> egg.StatusRequest
	3, // 5: egg.Egg.Kill:output_type -> egg.KillResponse
	5, // 6: egg.Egg.Resize:output_type -> egg.ResizeResponse
	6, // 7: egg.Egg.Session:output_type -> egg.SessionMsg
	1, // 8: egg.Egg.Status:output_type -> egg.StatusResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_egg_proto_init() }
func file_egg_proto_init() {
	if File_egg_proto != nil {
		return
	}
	file_egg_proto_msgTypes[6].OneofWrappers = []any{
		(*SessionMsg_Output)(nil),
		(*SessionMsg_Input)(nil),
		(*SessionMsg_Resize)(nil),
		(*SessionMsg_ExitCode)(nil),
		(*SessionMsg_Attach)(nil),
		(*SessionMsg_Detach)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egg_proto_rawDesc), len(file_egg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egg_proto_goTypes,
		DependencyIndexes: file_egg_proto_depIdxs,
		MessageInfos:      file_egg_proto_msgTypes,
	}.Build()
	File_egg_proto = out.File
	file_egg_proto_goTypes = nil
	file_egg_proto_depIdxs = nil
}
