// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: egg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpawnRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agent          string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Cwd            string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Rows           uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols           uint32                 `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	Isolation      string                 `protobuf:"bytes,6,opt,name=isolation,proto3" json:"isolation,omitempty"`
	Env            map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mounts         []*Mount               `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,9,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ResourceLimits *ResourceLimits        `protobuf:"bytes,10,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"`
	Skill          string                 `protobuf:"bytes,11,opt,name=skill,proto3" json:"skill,omitempty"`                                                                                 // skill name for logging/tracking
	Metadata       map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary key-value pairs
	Shell          string                 `protobuf:"bytes,13,opt,name=shell,proto3" json:"shell,omitempty"`                                                                                 // override shell (default: agent decides)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpawnRequest) Reset() {
	*x = SpawnRequest{}
	mi := &file_egg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnRequest) ProtoMessage() {}

func (x *SpawnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnRequest.ProtoReflect.Descriptor instead.
func (*SpawnRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{0}
}

func (x *SpawnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpawnRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SpawnRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SpawnRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *SpawnRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *SpawnRequest) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

func (x *SpawnRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SpawnRequest) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *SpawnRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *SpawnRequest) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

func (x *SpawnRequest) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *SpawnRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SpawnRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_egg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{1}
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuSeconds    uint32                 `protobuf:"varint,1,opt,name=cpu_seconds,json=cpuSeconds,proto3" json:"cpu_seconds,omitempty"`    // RLIMIT_CPU (0 = no limit)
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"` // RLIMIT_AS (0 = no limit)
	MaxFds        uint32                 `protobuf:"varint,3,opt,name=max_fds,json=maxFds,proto3" json:"max_fds,omitempty"`                // RLIMIT_NOFILE (0 = no limit)
	MaxPids       uint32                 `protobuf:"varint,4,opt,name=max_pids,json=maxPids,proto3" json:"max_pids,omitempty"`             // cgroup pids.max (0 = no limit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_egg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimits) GetCpuSeconds() uint32 {
	if x != nil {
		return x.CpuSeconds
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMaxFds() uint32 {
	if x != nil {
		return x.MaxFds
	}
	return 0
}

func (x *ResourceLimits) GetMaxPids() uint32 {
	if x != nil {
		return x.MaxPids
	}
	return 0
}

type SpawnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnResponse) Reset() {
	*x = SpawnResponse{}
	mi := &file_egg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnResponse) ProtoMessage() {}

func (x *SpawnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnResponse.ProtoReflect.Descriptor instead.
func (*SpawnResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SpawnResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_egg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_egg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Agent         string                 `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Isolation     string                 `protobuf:"bytes,6,opt,name=isolation,proto3" json:"isolation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_egg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{6}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInfo) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SessionInfo) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *SessionInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *SessionInfo) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

type KillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_egg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{7}
}

func (x *KillRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_egg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{8}
}

type ResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	mi := &file_egg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{9}
}

func (x *ResizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	mi := &file_egg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{10}
}

type SessionMsg struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SessionMsg_Output
	//	*SessionMsg_Input
	//	*SessionMsg_Resize
	//	*SessionMsg_ExitCode
	//	*SessionMsg_Attach
	//	*SessionMsg_Detach
	Payload       isSessionMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMsg) Reset() {
	*x = SessionMsg{}
	mi := &file_egg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMsg) ProtoMessage() {}

func (x *SessionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMsg.ProtoReflect.Descriptor instead.
func (*SessionMsg) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{11}
}

func (x *SessionMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMsg) GetPayload() isSessionMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SessionMsg) GetOutput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *SessionMsg) GetInput() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *SessionMsg) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *SessionMsg) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *SessionMsg) GetAttach() bool {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Attach); ok {
			return x.Attach
		}
	}
	return false
}

func (x *SessionMsg) GetDetach() bool {
	if x != nil {
		if x, ok := x.Payload.(*SessionMsg_Detach); ok {
			return x.Detach
		}
	}
	return false
}

type isSessionMsg_Payload interface {
	isSessionMsg_Payload()
}

type SessionMsg_Output struct {
	Output []byte `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

type SessionMsg_Input struct {
	Input []byte `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type SessionMsg_Resize struct {
	Resize *Resize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type SessionMsg_ExitCode struct {
	ExitCode int32 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type SessionMsg_Attach struct {
	Attach bool `protobuf:"varint,6,opt,name=attach,proto3,oneof"`
}

type SessionMsg_Detach struct {
	Detach bool `protobuf:"varint,7,opt,name=detach,proto3,oneof"`
}

func (*SessionMsg_Output) isSessionMsg_Payload() {}

func (*SessionMsg_Input) isSessionMsg_Payload() {}

func (*SessionMsg_Resize) isSessionMsg_Payload() {}

func (*SessionMsg_ExitCode) isSessionMsg_Payload() {}

func (*SessionMsg_Attach) isSessionMsg_Payload() {}

func (*SessionMsg_Detach) isSessionMsg_Payload() {}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_egg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{12}
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type VersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_egg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{13}
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_egg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_egg_proto_rawDescGZIP(), []int{14}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_egg_proto protoreflect.FileDescriptor

const file_egg_proto_rawDesc = "" +
	"\n" +
	"\tegg.proto\x12\x03egg\"\xb2\x04\n" +
	"\fSpawnRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\rR\x04cols\x12\x1c\n" +
	"\tisolation\x18\x06 \x01(\tR\tisolation\x12,\n" +
	"\x03env\x18\a \x03(\v2\x1a.egg.SpawnRequest.EnvEntryR\x03env\x12\"\n" +
	"\x06mounts\x18\b \x03(\v2\n" +
	".egg.MountR\x06mounts\x12'\n" +
	"\x0ftimeout_seconds\x18\t \x01(\rR\x0etimeoutSeconds\x12<\n" +
	"\x0fresource_limits\x18\n" +
	" \x01(\v2\x13.egg.ResourceLimitsR\x0eresourceLimits\x12\x14\n" +
	"\x05skill\x18\v \x01(\tR\x05skill\x12;\n" +
	"\bmetadata\x18\f \x03(\v2\x1f.egg.SpawnRequest.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05shell\x18\r \x01(\tR\x05shell\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x05Mount\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x88\x01\n" +
	"\x0eResourceLimits\x12\x1f\n" +
	"\vcpu_seconds\x18\x01 \x01(\rR\n" +
	"cpuSeconds\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12\x17\n" +
	"\amax_fds\x18\x03 \x01(\rR\x06maxFds\x12\x19\n" +
	"\bmax_pids\x18\x04 \x01(\rR\amaxPids\"@\n" +
	"\rSpawnResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"\r\n" +
	"\vListRequest\"<\n" +
	"\fListResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.egg.SessionInfoR\bsessions\"\xa3\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05agent\x18\x03 \x01(\tR\x05agent\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1c\n" +
	"\tisolation\x18\x06 \x01(\tR\tisolation\",\n" +
	"\vKillRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x0e\n" +
	"\fKillResponse\"V\n" +
	"\rResizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\"\x10\n" +
	"\x0eResizeResponse\"\xe2\x01\n" +
	"\n" +
	"SessionMsg\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\x06output\x18\x02 \x01(\fH\x00R\x06output\x12\x16\n" +
	"\x05input\x18\x03 \x01(\fH\x00R\x05input\x12%\n" +
	"\x06resize\x18\x04 \x01(\v2\v.egg.ResizeH\x00R\x06resize\x12\x1d\n" +
	"\texit_code\x18\x05 \x01(\x05H\x00R\bexitCode\x12\x18\n" +
	"\x06attach\x18\x06 \x01(\bH\x00R\x06attach\x12\x18\n" +
	"\x06detach\x18\a \x01(\bH\x00R\x06detachB\t\n" +
	"\apayload\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"\x10\n" +
	"\x0eVersionRequest\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\xa9\x02\n" +
	"\x03Egg\x12.\n" +
	"\x05Spawn\x12\x11.egg.SpawnRequest\x1a\x12.egg.SpawnResponse\x12+\n" +
	"\x04List\x12\x10.egg.ListRequest\x1a\x11.egg.ListResponse\x12+\n" +
	"\x04Kill\x12\x10.egg.KillRequest\x1a\x11.egg.KillResponse\x121\n" +
	"\x06Resize\x12\x12.egg.ResizeRequest\x1a\x13.egg.ResizeResponse\x12/\n" +
	"\aSession\x12\x0f.egg.SessionMsg\x1a\x0f.egg.SessionMsg(\x010\x01\x124\n" +
	"\aVersion\x12\x13.egg.VersionRequest\x1a\x14.egg.VersionResponseB0Z.github.com/ehrlich-b/wingthing/internal/egg/pbb\x06proto3"

var (
	file_egg_proto_rawDescOnce sync.Once
	file_egg_proto_rawDescData []byte
)

func file_egg_proto_rawDescGZIP() []byte {
	file_egg_proto_rawDescOnce.Do(func() {
		file_egg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egg_proto_rawDesc), len(file_egg_proto_rawDesc)))
	})
	return file_egg_proto_rawDescData
}

var file_egg_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_egg_proto_goTypes = []any{
	(*SpawnRequest)(nil),    // 0: egg.SpawnRequest
	(*Mount)(nil),           // 1: egg.Mount
	(*ResourceLimits)(nil),  // 2: egg.ResourceLimits
	(*SpawnResponse)(nil),   // 3: egg.SpawnResponse
	(*ListRequest)(nil),     // 4: egg.ListRequest
	(*ListResponse)(nil),    // 5: egg.ListResponse
	(*SessionInfo)(nil),     // 6: egg.SessionInfo
	(*KillRequest)(nil),     // 7: egg.KillRequest
	(*KillResponse)(nil),    // 8: egg.KillResponse
	(*ResizeRequest)(nil),   // 9: egg.ResizeRequest
	(*ResizeResponse)(nil),  // 10: egg.ResizeResponse
	(*SessionMsg)(nil),      // 11: egg.SessionMsg
	(*Resize)(nil),          // 12: egg.Resize
	(*VersionRequest)(nil),  // 13: egg.VersionRequest
	(*VersionResponse)(nil), // 14: egg.VersionResponse
	nil,                     // 15: egg.SpawnRequest.EnvEntry
	nil,                     // 16: egg.SpawnRequest.MetadataEntry
}
var file_egg_proto_depIdxs = []int32{
	15, // 0: egg.SpawnRequest.env:type_name -> egg.SpawnRequest.EnvEntry
	1,  // 1: egg.SpawnRequest.mounts:type_name -> egg.Mount
	2,  // 2: egg.SpawnRequest.resource_limits:type_name -> egg.ResourceLimits
	16, // 3: egg.SpawnRequest.metadata:type_name -> egg.SpawnRequest.MetadataEntry
	6,  // 4: egg.ListResponse.sessions:type_name -> egg.SessionInfo
	12, // 5: egg.SessionMsg.resize:type_name -> egg.Resize
	0,  // 6: egg.Egg.Spawn:input_type -> egg.SpawnRequest
	4,  // 7: egg.Egg.List:input_type -> egg.ListRequest
	7,  // 8: egg.Egg.Kill:input_type -> egg.KillRequest
	9,  // 9: egg.Egg.Resize:input_type -> egg.ResizeRequest
	11, // 10: egg.Egg.Session:input_type -> egg.SessionMsg
	13, // 11: egg.Egg.Version:input_type -> egg.VersionRequest
	3,  // 12: egg.Egg.Spawn:output_type -> egg.SpawnResponse
	5,  // 13: egg.Egg.List:output_type -> egg.ListResponse
	8,  // 14: egg.Egg.Kill:output_type -> egg.KillResponse
	10, // 15: egg.Egg.Resize:output_type -> egg.ResizeResponse
	11, // 16: egg.Egg.Session:output_type -> egg.SessionMsg
	14, // 17: egg.Egg.Version:output_type -> egg.VersionResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_egg_proto_init() }
func file_egg_proto_init() {
	if File_egg_proto != nil {
		return
	}
	file_egg_proto_msgTypes[11].OneofWrappers = []any{
		(*SessionMsg_Output)(nil),
		(*SessionMsg_Input)(nil),
		(*SessionMsg_Resize)(nil),
		(*SessionMsg_ExitCode)(nil),
		(*SessionMsg_Attach)(nil),
		(*SessionMsg_Detach)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egg_proto_rawDesc), len(file_egg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egg_proto_goTypes,
		DependencyIndexes: file_egg_proto_depIdxs,
		MessageInfos:      file_egg_proto_msgTypes,
	}.Build()
	File_egg_proto = out.File
	file_egg_proto_goTypes = nil
	file_egg_proto_depIdxs = nil
}
