// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: egg.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Egg_Kill_FullMethodName    = "/egg.Egg/Kill"
	Egg_Resize_FullMethodName  = "/egg.Egg/Resize"
	Egg_Session_FullMethodName = "/egg.Egg/Session"
	Egg_Status_FullMethodName  = "/egg.Egg/Status"
)

// EggClient is the client API for Egg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EggClient interface {
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error)
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMsg, SessionMsg], error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type eggClient struct {
	cc grpc.ClientConnInterface
}

func NewEggClient(cc grpc.ClientConnInterface) EggClient {
	return &eggClient{cc}
}

func (c *eggClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, Egg_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggClient) Resize(ctx context.Context, in *ResizeRequest, opts ...grpc.CallOption) (*ResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeResponse)
	err := c.cc.Invoke(ctx, Egg_Resize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eggClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMsg, SessionMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Egg_ServiceDesc.Streams[0], Egg_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMsg, SessionMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Egg_SessionClient = grpc.BidiStreamingClient[SessionMsg, SessionMsg]

func (c *eggClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Egg_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EggServer is the server API for Egg service.
// All implementations must embed UnimplementedEggServer
// for forward compatibility.
type EggServer interface {
	Kill(context.Context, *KillRequest) (*KillResponse, error)
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
	Session(grpc.BidiStreamingServer[SessionMsg, SessionMsg]) error
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedEggServer()
}

// UnimplementedEggServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEggServer struct{}

func (UnimplementedEggServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedEggServer) Resize(context.Context, *ResizeRequest) (*ResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resize not implemented")
}
func (UnimplementedEggServer) Session(grpc.BidiStreamingServer[SessionMsg, SessionMsg]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedEggServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEggServer) mustEmbedUnimplementedEggServer() {}
func (UnimplementedEggServer) testEmbeddedByValue()             {}

// UnsafeEggServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EggServer will
// result in compilation errors.
type UnsafeEggServer interface {
	mustEmbedUnimplementedEggServer()
}

func RegisterEggServer(s grpc.ServiceRegistrar, srv EggServer) {
	// If the following call panics, it indicates UnimplementedEggServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Egg_ServiceDesc, srv)
}

func _Egg_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egg_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egg_Resize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggServer).Resize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egg_Resize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggServer).Resize(ctx, req.(*ResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egg_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EggServer).Session(&grpc.GenericServerStream[SessionMsg, SessionMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Egg_SessionServer = grpc.BidiStreamingServer[SessionMsg, SessionMsg]

func _Egg_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EggServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Egg_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EggServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Egg_ServiceDesc is the grpc.ServiceDesc for Egg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Egg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "egg.Egg",
	HandlerType: (*EggServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kill",
			Handler:    _Egg_Kill_Handler,
		},
		{
			MethodName: "Resize",
			Handler:    _Egg_Resize_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Egg_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Egg_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "egg.proto",
}
